#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Test
  # forward declarations
  class MyMessage < ::ProtocolBuffers::Message; end

  class MyMessage < ::ProtocolBuffers::Message
    set_fully_qualified_name "Test.MyMessage"

    required :int64, :id, 1
    optional :string, :myField, 2
  end

end
